In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os,sys,time

In [2]:
projects = ["KIRC", "KIRP", "KICH", "LUSC", "LUAD", "BRCA", "LGG",
            "PRAD", "HNSC", "COAD", "STAD", "READ", "CESC", 
            "ESCA", "PAAD", "GBM"]

print(len(projects))

analysis_results = "analysis_results/"

16

In [3]:
n_sign_genes_all = np.zeros(len(projects))
for ip,project in enumerate(projects):
    df_padj = pd.read_csv(f"{analysis_results}/{project}_R.csv")

    p_adj = df_padj["p_adj"].values
    n_sign_genes = np.sum(p_adj < 0.05)
    print(n_sign_genes)

    n_sign_genes_all[ip] = n_sign_genes

10625
5626
60
6023
8733
16127
12700
8441
7254
7093
5411
3414
3114
2229
2020
103

In [4]:
df = pd.DataFrame(data = {"cohort": projects, "n_sign_genes": n_sign_genes_all})
df.to_csv(f"{analysis_results}n_sign_genes_16TCGA.csv", index=None)

df_sorted = df.sort_values(by="n_sign_genes", ascending=False)
df_sorted.to_csv(f"{analysis_results}n_sign_genes_16TCGA_sorted.csv", index=None)

In [5]:
df

   cohort  n_sign_genes
0    KIRC       10625.0
1    KIRP        5626.0
2    KICH          60.0
3    LUSC        6023.0
4    LUAD        8733.0
5    BRCA       16127.0
6     LGG       12700.0
7    PRAD        8441.0
8    HNSC        7254.0
9    COAD        7093.0
10   STAD        5411.0
11   READ        3414.0
12   CESC        3114.0
13   ESCA        2229.0
14   PAAD        2020.0
15    GBM         103.0

In [6]:
df_sorted

   cohort  n_sign_genes
5    BRCA       16127.0
6     LGG       12700.0
0    KIRC       10625.0
4    LUAD        8733.0
7    PRAD        8441.0
8    HNSC        7254.0
9    COAD        7093.0
3    LUSC        6023.0
1    KIRP        5626.0
10   STAD        5411.0
11   READ        3414.0
12   CESC        3114.0
13   ESCA        2229.0
14   PAAD        2020.0
15    GBM         103.0
2    KICH          60.0